---
header-includes:
- \usepackage{booktabs}
- \usepackage{makecell}
- \usepackage{float}
- \usepackage{longtable}
- \floatplacement{figure}{H} 
output:
  pdf_document:
    toc: false
    template: default.latex
geometry: margin=2.1cm
---

```{r setup-settings-and-metadata, echo = FALSE}
# define the relevant markdown settings
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  dpi = getOption("lpjmlstats.pdf_plot_dpi", 300),
  dev = getOption("lpjmlstats.graphics_device", "png"),
  crop = NULL
)
```



<!---
# Beginning of front page
-->
\begin{center}
~\par
\vspace{3cm}
{\LARGE LPJmL Benchmark Report} \par
\vspace{1cm}
`r attr(bench_data, 'author')` \par
\vspace{1cm}
`r Sys.Date()` \par
\vspace{2cm}
\textbf{Description} 
\par
`r attr(bench_data, "description")`
\par
\vspace{2cm}
\textbf{Simulation Table}

```{r print-simulation-table, results='asis'}
sim_table <- attr(bench_data, "sim_table")

# manually escape special character ":" and "_"
sim_table <-
  sim_table %>%
  dplyr::mutate_all(function(x) gsub("([_:]+)", "\\\\\\1", x))

# reorder columns as they should be displayed
tabl <- sim_table %>% dplyr::select(sim_names,
                                    sim_identifier,
                                    sim_type,
                                    lpjml_version)

# create and style table
knitr::kable(
  tabl,
  format = "latex",
  booktabs = TRUE,
  # use booktabs style
  escape = FALSE,
  # allow latex commands but depends on manual escaping
  col.names = c("Sim Name", "Sim Identifier", "Sim Type", "Version")
)  %>%
  kableExtra::kable_styling(font_size = 8,
                            latex_options = c("HOLD_position"))
```
\vspace{2cm}
\textbf{Simulation Paths}
```{r print-simulation-paths, results='asis'}
# select relevant columns and make font size of paths very small
tabl <- sim_table %>%
  dplyr::mutate(sim_paths = paste0("\\tiny ", sim_paths)) %>%
  dplyr::select(sim_identifier, sim_paths)

# create and style table
knitr::kable(
  tabl,
  format = "latex",
  booktabs = TRUE,
  escape = FALSE,
  col.names = c("Sim Identifier", "Sim Path")
) %>%
  kableExtra::kable_styling(font_size = 8,
                            latex_options = c("HOLD_position"))
```
\end{center}
\thispagestyle{empty}
\newpage
<!---
# End of front page
-->



<!---
# Beginning of main report
-->
```{r generate-report-content, results='asis', fig.height=2.4}
for (metric in bench_data) {
  # call plot and plot arrangement functions
  metric$generate_report_content()
  # separate report content of each metric
  cat("\n\n")
}
```
<!---
# End of main report
-->
